# Dependabot configuration for Mimir Deep Code Research System
# Enhanced automated dependency updates with comprehensive security focus
# Complements the custom dependency management workflows

version: 2
updates:
  # Python dependencies with enhanced security grouping
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 8
    reviewers:
      - "mimir-dev-team"
    assignees:
      - "mimir-dev-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "dependabot"
    # Enhanced dependency grouping for better management
    groups:
      critical-security:
        patterns:
          - "cryptography*"
          - "fastapi*"
          - "pydantic*"
          - "uvicorn*"
          - "httpx*"
          - "jinja2*"
        update-types:
          - "security"
        priority: 10
      development-tools:
        patterns:
          - "pytest*"
          - "black*"
          - "ruff*"
          - "mypy*"
          - "pre-commit*"
          - "bandit*"
          - "safety*"
          - "pip-audit*"
        update-types:
          - "minor"
          - "patch"
      web-framework:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "pydantic*"
          - "starlette*"
        update-types:
          - "minor"
          - "patch"
      ai-ml-stack:
        patterns:
          - "google-generativeai*"
          - "numpy*"
        update-types:
          - "minor"
          - "patch"
      code-analysis:
        patterns:
          - "tree-sitter*"
          - "GitPython*"
          - "msgpack*"
        update-types:
          - "patch"
    # Enhanced security policies
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
    # Controlled major version updates
    ignore:
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tree-sitter*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "google-generativeai"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "UTC"
    target-branch: "develop"
    open-pull-requests-limit: 5
    reviewers:
      - "@mimir-maintainers"
    assignees:
      - "@devops-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
    # Group container updates
    groups:
      base-images:
        patterns:
          - "python*"
          - "*alpine*"
          - "*slim*"
          - "*bookworm*"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
      - dependency-type: "indirect"
        update-type: "security-update"

  # GitHub Actions dependencies  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "UTC"
    target-branch: "develop"
    open-pull-requests-limit: 5
    reviewers:
      - "@mimir-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
    # Group related actions
    groups:
      security-actions:
        patterns:
          - "*security*"
          - "*codeql*"
          - "*trivy*"
          - "*bandit*"
      testing-actions:
        patterns:
          - "*test*"
          - "*coverage*"
          - "*pytest*"
      build-actions:
        patterns:
          - "*build*"
          - "*docker*"
          - "*setup*"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
      - dependency-type: "direct"
        update-type: "version-update:semver-major"

# Custom vulnerability alerts
# (These are configured in GitHub repository settings, not in this file)
# - Enable Dependabot security updates
# - Enable Dependabot version updates  
# - Configure notification preferences for security alerts
# - Set up integration with security scanning tools