# Prometheus Configuration for Mimir Production Environment
# Enhanced monitoring with alerting and long-term retention

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mimir-prod'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "rules/*.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Mimir MCP Server metrics
  - job_name: 'mimir-server'
    static_configs:
      - targets: ['mimir-server:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Mimir UI metrics
  - job_name: 'mimir-ui'
    static_configs:
      - targets: ['mimir-ui:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # NGINX reverse proxy metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true

  # Redis cache metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker container metrics (if cAdvisor is enabled)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: true

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write.yourdomain.com/api/v1/write"
#     basic_auth:
#       username: "mimir"
#       password: "your-password"

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true

# Web configuration
web:
  console.libraries: /etc/prometheus/console_libraries
  console.templates: /etc/prometheus/consoles
  enable-lifecycle: true
  enable-admin-api: true
  max-connections: 512
  read-timeout: 30s
  route-prefix: /